compat-wireless: fix compilation for 2.6.32
2.6.32 was the latest version using CONFIG_WIRELESS_EXT. Without this patch
compilation produced

net/wireless/wext-compat.c:443: error: ‘struct wireless_dev’ has no member named ‘wext’

since config.mk defined CONFIG_CFG80211_WEXT but autoconf.sh didn't.

Signed-off-by: Paul Fertser <fercerpav@gmail.com>