Some compilation fixes for 2.6.24 and 2.6.25
2.6.24 is still left disabled, we need to figure out a way to deal with
this still:

  CC      /home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.o
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c: In function ‘wireless_dev_seq_start’:
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:678: warning: statement with no effect
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:679: warning: ISO C90 forbids mixed declarations and code
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c: In function ‘wireless_dev_seq_next’:
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:695: warning: statement with no effect
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c: In function ‘seq_open_wireless’:
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:717: error: implicit declaration of function ‘seq_open_net’
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:718: error: invalid application of ‘sizeof’ to incomplete type ‘struct seq_net_private’
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c: At top level:
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:726: error: ‘seq_release_net’ undeclared here (not in a function)
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c: In function ‘wireless_nlevent_process’:
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:1339: warning: passing argument 2 of ‘rtnl_notify’ makes integer from pointer without a cast
include/linux/rtnetlink.h:618: note: expected ‘u32’ but argument is of type ‘struct net *’
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:1339: warning: passing argument 4 of ‘rtnl_notify’ makes pointer from integer without a cast
include/linux/rtnetlink.h:618: note: expected ‘struct nlmsghdr *’ but argument is of type ‘int’
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:1339: warning: passing argument 5 of ‘rtnl_notify’ makes integer from pointer without a cast
include/linux/rtnetlink.h:618: note: expected ‘gfp_t’ but argument is of type ‘void *’
/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.c:1339: error: too many arguments to function ‘rtnl_notify’
make[3]: *** [/home/mcgrof/devel/compat-wireless-2.6/net/wireless/wext.o] Error 1
make[2]: *** [/home/mcgrof/devel/compat-wireless-2.6/net/wireless] Error 2
make[1]: *** [_module_/home/mcgrof/devel/compat-wireless-2.6] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-2.6.24-24-generic'

Signed-off-by: Luis R. Rodriguez <lrodriguez@atheros.com>