compat-wireless: remove patches/49-rename_path_lookup.patch
This is no longer required as this was addressed upstream via:

commit 5ad20dd1480dc557afcec19ac7fae5581264dd59
Author: Luis R. Rodriguez <mcgrof@frijolero.org>
Date:   Tue Feb 7 21:09:25 2012 -0800

    mac80211: rename mesh static path_lookup()

    If you want to use mesh support from mac80211 on a recent
    kernel on 2.6.24 you'll run into a name clash when compiling
    against include/linux/namei.h, so rename this routine.

    /home/mcgrof/tmp/compat-wireless-3.2.5-1/net/mac80211/mesh_pathtbl.c: At top level:
    /home/mcgrof/tmp/compat-wireless-3.2.5-1/net/mac80211/mesh_pathtbl.c:342:26: error: conflicting types for ‘path_lookup’
    include/linux/namei.h:71:12: note: previous declaration of ‘path_lookup’ was here

    Although this could sit as a separate patch in compat-wireless it seems
    best to just merge upstream.

    Cc: Javier Cardona <javier@cozybit.com>
    Signed-off-by: Luis R. Rodriguez <mcgrof@frijolero.org>
    Acked-by: Javier Cardona <javier@cozybit.com>
    Signed-off-by: John W. Linville <linville@tuxdriver.com>

Signed-off-by: Luis R. Rodriguez <mcgrof@frijolero.org>